/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ElectronicForm: typeof import('./src/components/forms/ElectronicForm.vue')['default']
    ElectronicsDialog: typeof import('./src/components/dialogs/ElectronicsDialog.vue')['default']
    ElectronicTable: typeof import('./src/components/tables/ElectronicTable.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    LaptopDialog: typeof import('./src/components/dialogs/LaptopDialog.vue')['default']
    LaptopForm: typeof import('./src/components/forms/LaptopForm.vue')['default']
    LaptopTable: typeof import('./src/components/tables/LaptopTable.vue')['default']
    LaptopTables: typeof import('./src/components/tables/LaptopTables.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartphoneDialog: typeof import('./src/components/dialogs/SmartphoneDialog.vue')['default']
    SmartphoneForm: typeof import('./src/components/forms/SmartphoneForm.vue')['default']
    SmartphoneTable: typeof import('./src/components/tables/SmartphoneTable.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
